# Generated by Django 2.0.6 on 2019-03-05 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0050_auto_20190302_1819'),
        ('company', '0019_company_urlhash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_stockgst', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockgst', to='stockkeeping.Stockdata')),
            ],
        ),
    ]
