# Generated by Django 2.0.6 on 2019-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0002_stock_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='gst_input',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gst_input',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gst_output',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gst_output',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock_gst',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock_gst',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
