# Generated by Django 2.0.6 on 2019-03-05 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0003_auto_20190305_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_gst',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
