# Generated by Django 2.0.6 on 2019-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0004_stock_gst_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_gst',
            name='hsn',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
