# Generated by Django 2.0.6 on 2019-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0005_stock_gst_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gst_input',
            name='total_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gst_output',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
