# Generated by Django 2.0.6 on 2019-03-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0006_auto_20190305_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_output',
            name='gstin_self',
            field=models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gst_output',
            name='gstin_vendor',
            field=models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True),
        ),
    ]
