# Generated by Django 2.0.6 on 2019-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gst', '0007_auto_20190306_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_input',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_input',
            name='gstin_self',
            field=models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gst_input',
            name='gstin_vendor',
            field=models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gst_input',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_input',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_input',
            name='ugst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_output',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_output',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_output',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gst_output',
            name='ugst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
