# Generated by Django 2.0.6 on 2018-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_title',
            field=models.CharField(max_length=255),
        ),
    ]
