# Generated by Django 2.0.6 on 2018-09-17 08:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180915_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
