# Generated by Django 2.0.6 on 2018-09-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180917_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='GST', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='blog.categories'),
            preserve_default=False,
        ),
    ]
