# Generated by Django 2.0.6 on 2018-09-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Categorycount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.categories'),
        ),
    ]
