# Generated by Django 2.0.6 on 2018-09-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categories_categorycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Categorycount',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Categorycount',
        ),
    ]
