# Generated by Django 2.0.6 on 2018-09-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180920_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
