# Generated by Django 2.0.6 on 2018-09-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
