# Generated by Django 2.0.6 on 2018-10-27 10:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180926_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
