# Generated by Django 2.0.6 on 2019-02-26 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todogst', '0002_auto_20180922_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
