# Generated by Django 2.0.6 on 2019-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_integration', '0002_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
