# Generated by Django 2.0.6 on 2019-02-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_integration', '0003_auto_20190206_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='User',
        ),
    ]
