# Generated by Django 2.0.6 on 2019-02-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_integration', '0006_product_deactivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deactivate',
        ),
    ]
