# Generated by Django 2.0.6 on 2019-02-25 08:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
