# Generated by Django 2.0.6 on 2019-02-25 10:46

from django.db import migrations, models
import messaging.models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190225_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attchment',
            field=models.FileField(blank=True, upload_to='message_picture', validators=[messaging.models.file_size]),
        ),
    ]
