# Generated by Django 2.0.6 on 2018-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Qualification',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
