# Generated by Django 2.0.6 on 2018-10-10 13:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20180926_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
