# Generated by Django 2.0.6 on 2019-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20190204_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Bussiness User', 'Bussiness User'), ('Professional', 'Professional')], default='Bussiness User', max_length=32),
        ),
    ]
