# Generated by Django 2.0.6 on 2019-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_integration', '0003_auto_20190206_1803'),
        ('userprofile', '0011_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_products',
            field=models.ManyToManyField(blank=True, related_name='products_subscribed', to='ecommerce_integration.Product'),
        ),
    ]
