# Generated by Django 2.0.6 on 2019-02-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_integration', '0006_product_deactivate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0012_profile_subscribed_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('deactivate', models.BooleanField(default=False)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_activate', to='ecommerce_integration.Product')),
            ],
        ),
    ]
