# Generated by Django 2.0.6 on 2019-02-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_product_activation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_activation',
            old_name='activate',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product_activation',
            name='deactivate',
        ),
    ]
