# Generated by Django 2.0.6 on 2019-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190228_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='City',
            field=models.CharField(blank=True, default='Siliguri', max_length=100),
        ),
    ]
