# Generated by Django 2.0.6 on 2019-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='City',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
