# Generated by Django 2.0.6 on 2019-03-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_achivements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Skills',
            new_name='basic_info',
        ),
    ]
