# Generated by Django 2.0.6 on 2019-03-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_auto_20190315_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Qualification',
        ),
    ]
