# Generated by Django 2.0.6 on 2019-03-15 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_integration', '0007_auto_20190214_1734'),
        ('userprofile', '0026_remove_profile_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_1', models.FileField(blank=True, upload_to='pro_verification', validators=[userprofile.models.file_size])),
                ('upload_2', models.FileField(blank=True, upload_to='pro_verification', validators=[userprofile.models.file_size])),
                ('upload_3', models.FileField(blank=True, upload_to='pro_verification', validators=[userprofile.models.file_size])),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_product', to='ecommerce_integration.Product')),
            ],
        ),
    ]
