# Generated by Django 2.0.6 on 2019-03-16 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_auto_20190316_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
