# Generated by Django 2.0.6 on 2019-03-16 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0030_organisation_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation_member',
            name='member_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_staff_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
