# Generated by Django 2.0.6 on 2019-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0032_organisation_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_verify',
            name='u1_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro_verify',
            name='u2_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro_verify',
            name='u3_status',
            field=models.BooleanField(default=False),
        ),
    ]
