# Generated by Django 2.0.5 on 2018-09-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companyname', to='company.company'),
        ),
        migrations.AlterField(
            model_name='ledger1',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companys', to='company.company'),
        ),
    ]
