# Generated by Django 2.0.6 on 2018-09-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0002_auto_20180908_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger1',
            name='Ctotal',
        ),
        migrations.RemoveField(
            model_name='ledger1',
            name='Total_Debit',
        ),
    ]
