# Generated by Django 2.0.6 on 2018-09-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20180912_1942'),
        ('accounting_double_entry', '0003_auto_20180922_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='Company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_group', to='company.company'),
        ),
    ]
