# Generated by Django 2.0.6 on 2018-10-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0007_auto_20181002_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='group1_Name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_double_entry.group1'),
        ),
    ]
