# Generated by Django 2.0.7 on 2018-10-04 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0010_auto_20181002_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='End_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
