# Generated by Django 2.0.6 on 2018-10-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0011_journal_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='End_Date',
        ),
    ]
