# Generated by Django 2.0.6 on 2018-10-10 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0016_auto_20181010_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Journal',
        ),
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Ledger',
        ),
        migrations.RemoveField(
            model_name='selectdatefield',
            name='User',
        ),
        migrations.AddField(
            model_name='journal',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledger1',
            name='Creation_Date',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 14, 16, 10, 164740)),
        ),
        migrations.DeleteModel(
            name='selectdatefield',
        ),
    ]
