# Generated by Django 2.0.6 on 2018-10-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0019_auto_20181010_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='Creation_Date',
            field=models.DateField(default=datetime.datetime(2018, 10, 11, 12, 31, 9, 178535)),
        ),
    ]
