# Generated by Django 2.0.6 on 2018-10-12 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0020_auto_20181011_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='Creation_Date',
            field=models.DateField(default=datetime.datetime(2018, 10, 12, 6, 10, 57, 589702, tzinfo=utc)),
        ),
    ]
