# Generated by Django 2.0.6 on 2018-10-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0022_auto_20181012_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Journal',
        ),
        migrations.RemoveField(
            model_name='selectdatefield',
            name='Ledger',
        ),
        migrations.AlterField(
            model_name='selectdatefield',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
