# Generated by Django 2.0.6 on 2018-10-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0025_auto_20181013_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='start_date',
        ),
    ]
