# Generated by Django 2.0.6 on 2018-10-25 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0027_remove_ledger1_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectdatefield',
            name='End_Date',
            field=models.DateField(blank=True, default=datetime.date(2019, 3, 31), null=True),
        ),
        migrations.AlterField(
            model_name='selectdatefield',
            name='Start_Date',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 1), null=True),
        ),
    ]
