# Generated by Django 2.0.6 on 2018-10-26 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0028_auto_20181025_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='Creation_Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
