# Generated by Django 2.0.6 on 2018-10-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0029_auto_20181026_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='group1_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupledgers', to='accounting_double_entry.group1'),
        ),
    ]
