# Generated by Django 2.0.6 on 2018-10-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0030_auto_20181026_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='Opening_Balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ledger1',
            name='group1_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_double_entry.group1'),
        ),
    ]
