# Generated by Django 2.0.6 on 2018-10-27 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0031_auto_20181027_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='narration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
