# Generated by Django 2.0.6 on 2018-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0032_auto_20181027_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='Credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
