# Generated by Django 2.0.6 on 2018-11-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0033_auto_20181102_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger1',
            name='Opening_Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger1',
            name='group1_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_double_entry.group1'),
        ),
    ]
