# Generated by Django 2.0.6 on 2018-12-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0034_auto_20181103_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger1',
            name='Closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
