# Generated by Django 2.0.6 on 2018-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0036_auto_20181207_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger1',
            name='Balance_opening',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
