# Generated by Django 2.0.6 on 2018-12-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0044_auto_20181213_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group1',
            old_name='Group_behaves_like_a_Sub_Ledger',
            new_name='Group_behaves_like_a_Sub_Group',
        ),
    ]
