# Generated by Django 2.0.6 on 2018-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0045_auto_20181213_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='Nature_of_group1',
        ),
        migrations.AddField(
            model_name='group',
            name='Nature_of_group1',
            field=models.CharField(choices=[('Assets', 'Assets'), ('Expenses', 'Expenses'), ('Income', 'Income'), ('Liabilities', 'Liabilities'), ('Not Applicable', 'Not Applicable')], default='Assets', max_length=32),
        ),
    ]
