# Generated by Django 2.0.6 on 2018-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0046_auto_20181214_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='Total_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='group1',
            name='Total_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
