# Generated by Django 2.0.6 on 2019-01-18 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0016_auto_20190103_1923'),
        ('accounting_double_entry', '0050_auto_20190103_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particularspayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particularpayment', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamepayment', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payledgers', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.AddField(
            model_name='particularspayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting_double_entry.Payment'),
        ),
    ]
