# Generated by Django 2.0.6 on 2019-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0051_auto_20190118_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
