# Generated by Django 2.0.6 on 2019-01-19 07:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0016_auto_20190103_1923'),
        ('accounting_double_entry', '0052_auto_20190118_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particularsreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particularreceipt', to='accounting_double_entry.ledger1')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting_double_entry.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamereceipt', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptledgers', to='accounting_double_entry.ledger1')),
            ],
        ),
    ]
