# Generated by Django 2.0.6 on 2019-01-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0053_particularsreceipt_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularsreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting_double_entry.Receipt'),
        ),
    ]
