# Generated by Django 2.0.6 on 2019-01-21 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0056_auto_20190119_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multijournal',
            name='Date',
        ),
        migrations.AddField(
            model_name='multijournaltotal',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
