# Generated by Django 2.0.6 on 2019-01-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0057_auto_20190121_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multijournal',
            name='reference',
        ),
    ]
