# Generated by Django 2.0.6 on 2019-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0058_remove_multijournal_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multijournaltotal',
            name='Total_Credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='multijournaltotal',
            name='Total_Debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
