# Generated by Django 2.0.6 on 2019-01-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0059_auto_20190121_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multijournal',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='multijournal',
            name='User',
        ),
    ]
