# Generated by Django 2.0.6 on 2019-01-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0060_auto_20190121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='voucher_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
