# Generated by Django 2.0.6 on 2019-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0061_auto_20190125_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='voucher_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
