# Generated by Django 2.0.6 on 2019-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0062_auto_20190125_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
