# Generated by Django 2.0.6 on 2019-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0063_auto_20190125_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='voucher_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
