# Generated by Django 2.0.6 on 2019-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0065_auto_20190202_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularscontra',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
