# Generated by Django 2.0.6 on 2019-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0066_auto_20190202_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularscontra',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
