# Generated by Django 2.0.6 on 2019-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0067_auto_20190202_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='unique_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
