# Generated by Django 2.0.6 on 2019-02-28 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0068_group1_unique_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='unique_number',
        ),
        migrations.AlterField(
            model_name='group1',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
