# Generated by Django 2.0.6 on 2019-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0071_group1_urlhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='group_count',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
