# Generated by Django 2.0.6 on 2019-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0073_auto_20190301_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='group_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
