# Generated by Django 2.0.6 on 2019-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0074_auto_20190301_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='group_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
