# Generated by Django 2.0.6 on 2019-03-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0075_auto_20190301_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='group_count',
        ),
    ]
