# Generated by Django 2.0.6 on 2019-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0076_remove_group1_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
