# Generated by Django 2.0.6 on 2019-03-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0077_group1_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
