# Generated by Django 2.0.6 on 2019-03-06 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0020_auto_20190305_1825'),
        ('accounting_double_entry', '0080_auto_20190305_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='pl_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgerspl', to='accounting_double_entry.ledger1')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamepl', to='company.company')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgerspl', to='accounting_double_entry.ledger1')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
