# Generated by Django 2.0.6 on 2019-03-11 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0020_auto_20190305_1825'),
        ('accounting_double_entry', '0082_auto_20190306_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pl_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_expense', models.BooleanField(default=True)),
                ('it_head', models.CharField(choices=[('Salaries', 'Salaries'), ('Income_from_house_property', 'Income_from_house_property'), ('Profit_&_Gains_of_Business_and_Professions', 'Profit_&_Gains_of_Business_and_Professions'), ('Capital_Gains', 'Capital_Gains'), ('Income_from_other_sources', 'Income_from_other_sources')], default='Profit_&_Gains_of_Business_and_Professions', max_length=32)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamepl', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgerspl', to='accounting_double_entry.ledger1')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgerspl', to='accounting_double_entry.ledger1')),
            ],
        ),
    ]
