# Generated by Django 2.0.6 on 2019-03-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0083_pl_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pl_journal',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='pl_journal',
            name='User',
        ),
        migrations.RemoveField(
            model_name='pl_journal',
            name='by',
        ),
        migrations.RemoveField(
            model_name='pl_journal',
            name='to',
        ),
        migrations.DeleteModel(
            name='Pl_journal',
        ),
    ]
