# Generated by Django 2.0.6 on 2019-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0085_pl_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pl_journal',
            old_name='by',
            new_name='By',
        ),
        migrations.RenameField(
            model_name='pl_journal',
            old_name='to',
            new_name='To',
        ),
    ]
