# Generated by Django 2.0.6 on 2019-03-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0087_auto_20190311_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pl_journal',
            old_name='date',
            new_name='Date',
        ),
    ]
