# Generated by Django 2.0.5 on 2018-09-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyowner',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='companyowner',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='companyowner',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='companyowner',
        ),
    ]
