# Generated by Django 2.0.5 on 2018-09-08 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180908_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
