# Generated by Django 2.0.5 on 2018-09-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='User',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
