# Generated by Django 2.0.6 on 2018-10-06 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20180912_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='End_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='Start_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
