# Generated by Django 2.0.6 on 2018-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20181006_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Mobile_No',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
