# Generated by Django 2.0.6 on 2018-10-25 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20181006_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Books_Begining_From',
            field=models.DateTimeField(default=datetime.date(2018, 4, 1)),
        ),
        migrations.AlterField(
            model_name='company',
            name='Financial_Year_From',
            field=models.DateTimeField(default=datetime.date(2018, 4, 1)),
        ),
    ]
