# Generated by Django 2.0.6 on 2018-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20181102_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(max_length=18),
        ),
    ]
