# Generated by Django 2.0.6 on 2018-11-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20181102_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
