# Generated by Django 2.0.6 on 2019-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20190122_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
