# Generated by Django 2.0.6 on 2019-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
