# Generated by Django 2.0.6 on 2019-02-04 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancies', to='consultancy.consultancy'),
        ),
    ]
