# Generated by Django 2.0.6 on 2019-02-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0002_auto_20190211_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
