# Generated by Django 2.0.6 on 2018-10-27 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0010_auto_20181025_1917'),
        ('accounting_double_entry', '0031_auto_20181027_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compoundunits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('ref_no', models.PositiveIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Simpleunits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('formal', models.CharField(max_length=32)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=32)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stockgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantities', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_group', to='accounting_double_entry.group1')),
            ],
        ),
        migrations.AddField(
            model_name='stockdata',
            name='under',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stockkeeping.Stockgroup'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='unitcomplex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconds_unit', to='stockkeeping.Compoundunits'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='unitsimple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firsts_unit', to='stockkeeping.Simpleunits'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stockkeeping.Stockgroup'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Party_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partyledger', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseledger', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='compoundunits',
            name='firstunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firsts', to='stockkeeping.Simpleunits'),
        ),
        migrations.AddField(
            model_name='compoundunits',
            name='secondunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seconds', to='stockkeeping.Simpleunits'),
        ),
    ]
