# Generated by Django 2.0.6 on 2018-10-29 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0003_auto_20181029_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
