# Generated by Django 2.0.6 on 2018-11-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0006_auto_20181101_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Purchase_T',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_total', to='stockkeeping.Purchase_Total'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stockkeeping.Stockdata'),
        ),
    ]
