# Generated by Django 2.0.6 on 2018-11-01 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0011_auto_20181029_1803'),
        ('stockkeeping', '0010_auto_20181101_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase_total',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='purchase_total',
            name='User',
        ),
        migrations.RemoveField(
            model_name='purchase_total',
            name='purchases',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Purchase_T',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='rate',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Total_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Purchase_Total',
        ),
        migrations.AddField(
            model_name='stock_total',
            name='purchases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasetotal', to='stockkeeping.Purchase'),
        ),
        migrations.AddField(
            model_name='stock_total',
            name='stockitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasestock', to='stockkeeping.Stockdata'),
        ),
    ]
