# Generated by Django 2.0.6 on 2018-11-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0011_auto_20181101_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='rate',
        ),
        migrations.AddField(
            model_name='stock_total',
            name='Disc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
