# Generated by Django 2.0.6 on 2018-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0013_auto_20181101_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Name',
        ),
        migrations.AlterField(
            model_name='stock_total',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
