# Generated by Django 2.0.6 on 2018-11-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0015_purchase_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='hsn',
            field=models.PositiveIntegerField(),
        ),
    ]
