# Generated by Django 2.0.6 on 2018-11-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0016_auto_20181102_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
