# Generated by Django 2.0.6 on 2018-11-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0018_stock_total_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
