# Generated by Django 2.0.6 on 2018-11-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0019_auto_20181102_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_total',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='stock_total',
            name='User',
        ),
    ]
