# Generated by Django 2.0.6 on 2018-11-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0020_auto_20181102_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stockitem',
        ),
    ]
