# Generated by Django 2.0.6 on 2018-11-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0022_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salestotal', to='stockkeeping.Sales'),
        ),
    ]
