# Generated by Django 2.0.6 on 2018-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0024_auto_20181102_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total',
            name='Total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
