# Generated by Django 2.0.6 on 2018-11-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0025_stock_total_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_total',
            name='Total_sales',
        ),
    ]
