# Generated by Django 2.0.6 on 2018-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0031_sales_billname'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='billname',
            field=models.CharField(default='Supplier', max_length=32),
        ),
    ]
