# Generated by Django 2.0.6 on 2018-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0032_purchase_billname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
