# Generated by Django 2.0.6 on 2018-11-05 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0033_auto_20181105_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='stock_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
