# Generated by Django 2.0.6 on 2018-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0034_stockdata_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='Total_qty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
