# Generated by Django 2.0.6 on 2018-12-03 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0034_auto_20181103_1350'),
        ('stockkeeping', '0037_auto_20181105_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='Date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='daterange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockrange', to='accounting_double_entry.selectdatefield'),
        ),
    ]
