# Generated by Django 2.0.6 on 2018-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0038_auto_20181203_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='Total_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='qty_purchas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='qty_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
