# Generated by Django 2.0.6 on 2018-12-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0039_auto_20181206_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='Total_P',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Total_PS',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Total_S',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Total_qty',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='qty_purchas',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='qty_sale',
        ),
    ]
