# Generated by Django 2.0.6 on 2018-12-08 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0040_auto_20181206_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='batch_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='exp_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='man_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
