# Generated by Django 2.0.6 on 2018-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0041_auto_20181208_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='batch_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
