# Generated by Django 2.0.6 on 2019-01-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0044_auto_20190112_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgroup',
            name='under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_group', to='stockkeeping.Stockgroup'),
        ),
    ]
