# Generated by Django 2.0.6 on 2019-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0045_auto_20190112_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_name',
            field=models.CharField(max_length=32),
        ),
    ]
