# Generated by Django 2.0.6 on 2019-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0046_auto_20190112_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_total_sales',
            name='Quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
