# Generated by Django 2.0.6 on 2019-03-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0047_auto_20190116_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundunits',
            old_name='secondunit',
            new_name='seconds_unit',
        ),
        migrations.AddField(
            model_name='compoundunits',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compoundunits',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='simpleunits',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleunits',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='unitcomplex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconds_unit_complex', to='stockkeeping.Compoundunits'),
        ),
    ]
