# Generated by Django 2.0.6 on 2019-03-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0055_auto_20190306_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cgst_total',
            new_name='cgst_alltotal',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='gst_total',
            new_name='gst_alltotal',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='cgst_total',
            new_name='cgst_alltotal',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='gst_total',
            new_name='gst_alltotal',
        ),
    ]
