# Generated by Django 2.0.6 on 2019-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0056_auto_20190306_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total_sales',
            name='cgst_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock_total_sales',
            name='gst_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
